default: &default
  adapter: mysql2
  username: root
  password: kaito123
  host: 127.0.0.1
  encoding: utf8
  pool: 5
  reconnect: false

development:
  <<: *default
  database: project_figure_dev

test:
  <<: *default
  database: project_figure_test

production:
  <<: *default
  database: project_figure_production