default: &default
  adapter: postgresql
  host: 127.0.0.1
  encoding: utf8
  pool: 5
  username: namkidd
  password: kaito123
  reconnect: false

development:
  <<: *default
  database: pro_okr

test:
  <<: *default
  database: pro_okr_test